---
codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  ignore:
    # Rust backend is now included in coverage:
    # - Comprehensive Rust tests have been added (17 tests covering sorting, filtering, file I/O)
    # - The Rust code contains business logic (sort_images with complex filtering)
    # - Algorithms and data structures that benefit from coverage tracking
    # - File I/O operations with error handling that should be tested
    #
    # Exclude Rust build artifacts and generated files
    - "src-tauri/target/**"
    - "src-tauri/gen/**"
    - "node_modules/**"
    - "**/*.d.ts"
    - "**/*.config.*"
    - "**/main.ts"
    - "**/main.js"
    - "**/main.tsx"
    - ".github/**"
    - "coverage/**"
    # Type definitions don't have runtime code to test - TypeScript compiler validates them
    - "src/types.ts"
    # React components (.tsx) are excluded from coverage for the following reasons:
    # 1. Most components are presentational/UI wrappers around state management
    # 2. Business logic is tested in .ts files (handlers, core, utils, ui modules)
    # 3. React component testing requires significant setup and mocking overhead
    # 4. TypeScript provides compile-time safety for component props and types
    #
    # React component tests should be added if:
    # - Components contain complex business logic that isn't tested elsewhere
    # - Components have complex user interactions that need integration testing
    # - Components have state management logic that's difficult to test via integration
    # - Examples: notification.test.tsx (tests timer logic and state management)
    - "**/*.tsx"

  status:
    project:
      default:
        target: 70%
        threshold: 1%
    patch:
      default:
        target: 70%
